name = "prudentia-digital-website"
main = "worker.js"
compatibility_date = "2026-04-12"

[build]
command = "npm run build"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
